account/urls.py
from django.urls import path, re_path
from . import views

app_name = 'account'

urlpatterns = [
    path('<username>',views.profile_pg,name='profile_pg'),
    path('registration/', views.register,name='register'),
    path('login/',views.my_login,name='login'),
    path('logout/',views.my_logout,name='logout'),
    path('change/', views.profileChange,name='change'),
]

django_lab/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/shop/', permanent=True)),
    path('shop/',include('shop.urls',namespace='shop')),
    path('profile/',include('account.urls',namespace='account')),
    path('basket/', include('basket.urls',namespace='basket'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, re_path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search,name='searchbar'),
    path('contacts/', views.contacts,name='contacts'),
    path('<character_slug>/',views.index, name='company_sort'),
    path('brawl/<brawl_slug>', views.brawl, name='brawl_page'),
]

account/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User

#Модель профиля
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    number = models.CharField(max_length=12,null=True)
    birth_date = models.DateField(null=True)
    
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)
# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
#Создание формы для регистрации
class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password_confirm']:
            raise forms.ValidationError('Пароли не совпадают.')
        return cd['password_confirm']

#Создание формы для входа
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
#Создание формы для редактирования
class UserEdit(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name' , 'email')

#Создание формы для редактирования
class ProfileEdit(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"
        exclude = ['user']

account/views.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from basket.models import Order
# Create your views here.

#view страницы профиля
def profile_pg(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    return render(request, 'profile.html', {'profile': profile, 'user':user})

#view страницы регистрации
def register(request):
    if request.method == "POST":
        reg_form = RegisterForm(request.POST)
        if reg_form.is_valid():
            new_user = reg_form.save(commit=False)
            new_user.set_password(reg_form.cleaned_data['password'])
            new_user.save()
            profile = Profile.objects.create(user=new_user)
            return redirect(to='/profile/login/')
    else:
        reg_form = RegisterForm()
    return render(request, 'register.html', {'reg_form': reg_form})

#view страницы входа
def my_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(to='/shop/')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})

#view страницы выхода
def my_logout(request):
    logout(request)
    return redirect(to='/shop/')

#view страницы редактирования
def profileChange(request):
    if request.method == 'POST':
        user_form = UserEdit(instance=request.user, data=request.POST)
        profile_form = ProfileEdit(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect(to='/profile/{}'.format(request.user.get_username()))
    else:
        user_form = UserEdit(instance=request.user)
        profile_form = ProfileEdit(instance=request.user.profile)
        return render(request,
                      'change.html',
                      {'user_form': user_form,
                       'profile_form': profile_form})

account/templates/change.html
{% extends 'base.html' %}
{% block content %}
<div class="d-flex flex-column mb-3 border-3 my-5 w-50 mx-auto p-5">

       <div class="card-title nth-card-title">
          <h4>Изменение профиля</h4>
       </div>
       <form method="post" enctype="multipart/form-data" class="d-flex ">
          {% csrf_token %}
          
         <div>
          {{ profile_form.as_p}}
          
         </div>
         <div class="ms-5"> 
            {{ user_form.as_p }}
            <div class="d-grid gap-2 d-md-block mt-2">
              <button type="submit" class="">Подтвердить изменение профиля</button>
              </div>
           </div>
       </form>
 </div>
{% endblock %}

account/templates/history.html
{%extends "base.html"%}

{% block content %}
    <div class="d-flex flex-column align-items-center">
        <h3 class="my-5">История заказов</h3>
        {%if orders%}
            {%for order in orders%}
        <div class="d-flex mx-auto mt-5 mb-0 border w-50 text-center justify-content-center">
            <p class="me-5 my-5">Общая сумма заказа {{order.all_price}}</p>
            <p class="me-5 my-5">Дата заказа {{order.datetime}}</p>
        </div>
        {%endfor%}
            {%endif%}
    </div>  
{% endblock %}

account/templates/login.html
{% extends "base.html" %}
{% block content%}
    {% if form.errors %}
        <p >Ошибка в имени пользователя/пароле. Пожалуйста, попробуйте снова</p>
    {% endif %}
    {% if next %}
  {% if user.is_authenticated %}
    <p>Вы не имеете доступа для просмотра этой страницы</p>
  {% else %}
    <p>Пожалуйста, войдите или создайте аккаунт</p>
  {% endif %}
{% endif %}
<div class="d-flex flex-column w-50 align-items-center border-3 p-4 text-right mx-auto" style="margin-top: 180px;">
<form method="post" action="{% url 'account:login' %}" class="d-flex flex-column align-items-center">
{% csrf_token %}
        <div class="d-flex">
            <p class="me-3" style="width: 77px;">Никнейм:</p><p> {{form.username}}</p>
        </div>
        <div class="d-flex">
            <p class="me-3" style="width: 77px;">Пароль: </p><p>{{form.password}}</p>
        </div>


<input type="submit" value="Войти" class="btn-alert my-3"  />
<input type="hidden" name="next" value="{{ next }}" />
</form>
</div>

{% endblock %}

account/templates/profile.html
{% extends "base.html" %}

{% block content%}
    <div class="d-flex align-items-center" style="margin-left: 20vw;">
    <div class="d-flex flex-column mx-auto p-5 border-2 my-5 " style="width: 60%;">
        <p>Юзернейм:  {%if user.username%} {{user.username}} {% else %} Не указана {%endif%}</p>
        <p>E-mail: {%if user.email%} {{user.email}} {% else %} Не указана {%endif%}</p>
        <p>Дата рождения: {%if profile.birth_date%} {{profile.birth_date}} {% else %} Не указана {%endif%}</p>
        <p>Номер:{%if profile.number %} {{profile.number}} {% else %} Не указан{%endif%}</p>
        <p>Имя:{%if user.first_name %} {{user.first_name}} {% else %} Не указано {%endif%}</p>
        <p>Фамилия:{%if user.last_name %} {{user.last_name}} {% else %} Не указана {%endif%}</p>
        <a class="btn-alert text-decoration-none text-center p-1" href="{% url 'account:change' %}"> Редактировать </a>
        
    </div>
</div>
    
{% endblock %}

account/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="d-flex flex-column w-50 align-items-center text-right mx-auto" style="margin-top: 130px;">
        <p>Регистрация:</p>
        <form action="." method="post" class="d-grid">
            {{reg_form.as_p}}
            {% csrf_token %}
            <p><input type="submit" value="Создать аккаунт" class="btn-alert"></p>
        </form>
    </div> 
{% endblock %}