basket/urls.py
from django.urls import path, re_path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.baskets, name='basket'),
    path('order/',views.order_items, name='order'),
]

django_lab/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/shop/', permanent=True)),
    path('shop/',include('shop.urls',namespace='shop')),
    path('profile/',include('account.urls',namespace='account')),
    path('basket/', include('basket.urls',namespace='basket'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, re_path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search,name='searchbar'),
    path('contacts/', views.contacts,name='contacts'),
    path('<character_slug>/',views.index, name='company_sort'),
    path('brawl/<brawl_slug>', views.brawl, name='brawl_page'),
]

basket/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Brawl
import datetime

# Create your models here.

#Модель для промежуточной таблицы Корзины
class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    brawl = models.ForeignKey(Brawl, on_delete=models.CASCADE)

#Модель для Заказа
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    card = models.CharField(max_length=300)
    CVC = models.IntegerField()
    city = models.CharField(max_length=300)
    datetime = models.DateField(default=datetime.datetime.now().strftime("%Y-%m-%d"))
    all_price = models.FloatField()

basket/forms.py
from django import forms
from .models import *


#форма для заказа
class Order(forms.ModelForm):
    class Meta:
        model = Order
        fields = "__all__"
        exclude = ['user','datetime','all_price']

basket/views.py
from django.shortcuts import render
from .models import *
from .forms import *
from shop.models import Brawl



# Create your views here.
#view Корзины
def baskets(request):
    basket = Basket.objects.filter(user = request.user)
    all_price = 0
    for i in basket:
        all_price += i.brawl.price
    else:
        return render(request, 'basket.html', {'basket': basket,'all_price':all_price})

#view заказа
def order_items(request):
    basket = Basket.objects.filter(user = request.user)
    order_form = Order(request.POST)
    all_price = 0
    for i in basket:
        all_price += i.brawl.price
        i.brawl.order_count +=1
        i.brawl.save()
    if request.method == 'POST':
        if order_form.is_valid:
            preform = order_form.save(commit=False)
            preform.user = request.user
            preform.all_price = all_price
            preform.save()
            for item in basket:
                item.delete()
            return render(request,'finished.html')
    else:
        return render(request, 'order.html', {'form': order_form})
    

basket/templates/basket.html
{% extends "base.html" %}
{% block content %}
    <div class="d-flex flex-column align-items-center" style="width: 70vw;">
        <div class="d-flex" style="flex-wrap: wrap;">
        {%if basket%}
            {%for i in basket%}
            <div class="item  d-flex m-3 border-2 flex-column  align-items-center" style="width: 250px;height: 200px;">
                <a href="{{ i.brawl.get_absolute_url }}"  class="w-25 text-center align-items-center text-decoration-none text-secondary d-flex flex-column mx-5"><p style="width: 200px;"><img src="{{i.brawl.image.url}}" style="max-height: 100px;">{{i.brawl.character.title}} {{ i.brawl.name }}</p><br/>{{ i.brawl.price }} Р</a>
            </div>
        {%endfor%}
        </div>
            
        <div class="d-flex mx-auto mt-5 mb-5 border-3 w-25 text-center justify-content-center">
            <p>Итого: {{all_price}}</p>
        </div>
        <div class="d-flex mx-auto mt-5 my-5 border-3 w-50 text-center justify-content-center">
            <a href="{%url 'basket:order'%}" class="btn-alert d-flex text-center text-decoration-none">Оформить заказ</a>
        </div>
    </div>  
    {%else%}
    <p>У вас нет товаров</p>
    {%endif%}
{% endblock %}

basket/templates/finished.html
{%extends "base.html"%}

{%block content%} 
<div class="d-flex mx-auto mt-5 mb-0 border w-50 text-center justify-content-center">
    <p class="me-5 my-5">Оформление заказа завершёно</p>
</div>
{%endblock%}

basket/templates/order.html
{% extends 'base.html' %}

{% block content %}
    <div class="d-flex flex-column border-3 align-items-center text-right mx-auto" style="margin-top: 130px; width: 70vw">
        <p>Оформление заказа:</p>
        <form action="." method="post" class="d-flex flex-column my-4">
            {% csrf_token %}
            <div class="d-grid" style="grid-template-columns: 150px 700px; align-items:center ; justify-content: center;">
            {{form.as_p}}
            </div>
            <input type="submit" value="Заказать" class="btn-alert">
        </form>
    </div> 
{% endblock %}