account/urls.py
from django.urls import path, re_path
from . import views

app_name = 'account'

urlpatterns = [
    path('<username>',views.profile_pg,name='profile_pg'),
    path('registration/', views.register,name='register'),
    path('login/',views.my_login,name='login'),
    path('logout/',views.my_logout,name='logout'),
    path('change/', views.profileChange,name='change'),
]

basket/urls.py
from django.urls import path, re_path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.baskets, name='basket'),
    path('order/',views.order_items, name='order'),
]

django_lab/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/shop/', permanent=True)),
    path('shop/',include('shop.urls',namespace='shop')),
    path('profile/',include('account.urls',namespace='account')),
    path('basket/', include('basket.urls',namespace='basket'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, re_path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search,name='searchbar'),
    path('contacts/', views.contacts,name='contacts'),
    path('<character_slug>/',views.index, name='company_sort'),
    path('brawl/<brawl_slug>', views.brawl, name='brawl_page'),
]

shop/models.py
from django.db import models
from django.shortcuts import render,reverse, get_object_or_404
# Create your models here.


class Character(models.Model):
    title = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=50, db_index=True, unique=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('shop:company_sort',
                        args=[self.slug])

           

class Brawl(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, db_index=True, unique=True)
    image = models.ImageField(upload_to='django_lab/media/')
    price = models.IntegerField()
    available = models.BooleanField()
    views_count = models.IntegerField()
    order_count = models.IntegerField()
    
    def __str__(self):
        return self.character.title + ' ' + self.name
    
    def get_absolute_url(self):
        return reverse('shop:brawl_page',
                       args=[self.slug])

shop/views.py
from django.shortcuts import render,reverse, get_object_or_404
from .models import *
from basket.models import Basket
from django.db.models import Q
# Create your views here.

#view основной страницы
def index(request,character_slug=None):
    character = None
    characters = Character.objects.all()
    brawls = Brawl.objects.filter(available=True)
    
    if character_slug:
        character = get_object_or_404(Character, slug=character_slug)
        brawls = brawls.filter(character=character)
        

    if request.method == "POST":
        brawl_slug = request.POST.get("add_basket")
        brawl = Brawl.objects.get(slug=brawl_slug)
        order = Basket.objects.create(user = request.user, brawl=brawl)
        
        
    return render(request,
                  'index.html',
                  {'company': character,
                   'companies': characters,
                   'products': brawls,})

#view страницы телефона
def brawl(request,brawl_slug):
   
    brawl = get_object_or_404(Brawl,slug=brawl_slug)
    
    brawl.views_count += 1
    brawl.save()
    
    if request.method == "POST":
        brawl_slug = request.POST.get("add_basket")
        brawl = Brawl.objects.get(slug=brawl_slug)
        order = Basket.objects.create(user = request.user, brawl=brawl)
    
    return render(request,"brawl.html",{'brawl':brawl})


#view поиска
def search(request):
    req = request.GET.get('searchbar')
    serach_result = Brawl.objects.filter(Q(name__icontains=req) | Q(slug__icontains=req) | Q(character__title__icontains=req))
    return render(request, 'search.html', {'results':serach_result,'req': req})
    
def contacts(request):
    return render(request, 'contacts.html')

shop/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}<title>Local Library</title>{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    {% load static %}
</head>

<body class="h-100 d-grid" style="grid-template-columns: 220px 800px; position: absolute;">
        <div id="sidebar" class="nav nav-pills flex-column mb-auto bg-secondary" style="height :100%; width: 200px;">
        <div style="position: fixed; width: 200px;">
        <ul class="d-flex align-items-center justify-content-center text-center d-flex flex-column p-0 w-100" style="list-style-type: none;">
            {%if user.is_authenticated%}
            <li class="my-4 mx-auto">
                <a class="text-decoration-none text-white" href="{% url 'account:profile_pg' username=request.user.username%}">Профиль</a>
            </li> 
            <li class="my-4 mx-auto">
                <a class="text-decoration-none text-white" href="{% url 'account:logout'%}">Выйти</a>
            </li> 
            <li class="d-flex mx-auto my-2 w-100 text-center align-items-center btn-alert justify-content-center " >
                <a href="{% url 'basket:basket' %}" class="my-2 text-decoration-none text-white">Корзина</a>
            </li>
            {%else%}
            <li class="my-4 mx-auto">
                <a  class="text-decoration-none text-white" href="{% url 'account:login'%}">Войти</a>
            </li>
            <li  class="my-4 mx-auto">
                <a  class="text-decoration-none text-white" href="{% url 'account:register'%}">Зарегистрироваться</a>
            </li>
            {%endif%}
                <li class="my-4 mx-auto">
                    <a  class="text-decoration-none text-white" href="{% url 'shop:index'%}">Каталог</a>
                </li>
                {%if user.is_superuser%}
                <li class="my-4 mx-auto">
                    <a  class="text-decoration-none text-white" href="/admin/">Админ</a>
                </li>
                {%endif%}
                <li class="my-4 mx-auto">
                    <a  class="text-decoration-none text-white" href="{% url 'shop:contacts'%}">Контакты</a>
                </li>
                
                <li  class="mt-4 mx-auto">
                    <a  class="text-decoration-none text-white">Поиск</a>
                </li>
                <form action="{% url 'shop:searchbar' %}"  class="d-flex flex-column align-items-center  w-100 my-3">
                    
                    <input name="searchbar" type="text" placeholder="Search..." style="width: 50%;">
                </form>
            </div>
        </ul>
    </div>
    <div>
        
                {% block content %}{% endblock %}
                {% block pagination %}
                {%if is_paginated%}
                <div class = "pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous%}
                        <a href="{{request.path}}?page={{page_obj.previous_page_number}}">Prev</a>
                        {%endif%}
                        <span>
                              &nbsp; Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}&nbsp;
                        </span>
                        {% if page_obj.has_next%}
                        <a href="{{request.path}}?page={{page_obj.next_page_number}}">Next</a>
                        {%endif%}
                    </span>
                </div>
                {%endif%}


                {% endblock %}
            </div>

</body>
</html>

shop/templates/brawl.html
{%extends "base.html"%}

{% block content %}

<div class="d-flex flex-column align-items-center">
    <h3>{{phone.company.title}} {{phone.series}} {{phone.version}}</h3>
</div>
<div class="d-flex align-items-center mx-auto my-5 p-3 justify-content-center align-items-center" style="width: 1200px;">
    <div class="d-flex flex-column">
    <p class="mx-3 my-5">Персонаж: {{brawl.character.title}}</p>
    <img src="{{brawl.image.url}}" height="300px" class="me-5">
    <p class="mx-3 my-0">Количество заказов: {{brawl.order_count}}</p>  
    <p class="mx-3 my-0">Количество просмотров: {{brawl.views_count}}</p>
        
    </div>  
    <div>
        <p class="mx-3 my-5">Скин: {{brawl.name}}</p>
        <p class="mx-3 my-5">Цена: {{brawl.price}}</p>
        
        <form method="post">
            {% csrf_token %}
            <button class=" mx-3" type="submit" name="add_basket" value="{{brawl.slug}}">Добавить в корзину</button>
        </form>
    </div>
    
    
</div>

{% endblock %}

shop/templates/contacts.html
{%extends "base.html"%}
{%block content%}
<div class="d-flex flex-column">
    <p class="my-5">Впишите сюда контакты</p>
    <p class="my-5">И сюда</p>
    <p class="my-5">Сюда тоже можно</p>
</div>

{%endblock%}

shop/templates/index.html
{% extends "base.html"%}

{% block content %}
<div class="d-grid" style="grid-template-columns: 200px 10vw;">
    <div style="position: fixed; margin-top: 100px;">
    <div id="navbar" class="nav nav-pills flex-column mb-auto w-100 align-items-center my-4 justify-content-center">
        <ul class="d-flex flex-column justify-content-between bg-secondary ms-5 p-0">
            <li class="d-inline mx-5 my-4" {% if not company %} class="selected d-inline mx-5"{% endif %}>
                <a href="{% url "shop:index" %}" class="btn-alert text-dark px-3 py-1" style="text-decoration: none;">Все</a>
            </li>
            {% for c in companies %}   
                <li class="d-inline mx-5 my-4" {% if company.slug == c.slug %} class="selected d-inline text-white mx-5" {% endif %}>
                    <a href="{{ c.get_absolute_url }}" class="btn-alert text-dark px-3 py-1" style="text-decoration: none;">{{ c.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
    <div class="d-flex flex-column mx-5 justify-content-between  ">
        
        <div class="d-flex my-5" style="flex-wrap: wrap; width: 70vw;margin-left: 250px;">
            {% for product in products %}
            <br/>
                <div class="item  d-flex m-3 border-2 flex-column  align-items-center" style="width: 250px;height: 200px;">
                    <a href="{{ product.get_absolute_url }}"  class="w-25 text-center align-items-center text-decoration-none text-secondary d-flex flex-column mx-5"><p style="width: 200px;"><img src="{{product.image.url}}" style="max-height: 100px;">{{product.character.title}} {{ product.name }}</p><br/>{{ product.price }} Р</a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

shop/templates/search.html
{%extends "base.html"%}

{%block content%}
    <div class="d-flex flex-column mx-5 align-items-center " style="width: 80vw;">
            <h3 class="my-5">Результаты поиска по запросу {{req}}</h3>
        <div class="d-flex my-5 w-100" style="flex-wrap: wrap;">
            {% for result in results %}
            <br/>
                <div class="item  d-flex m-3 border-2 flex-column  align-items-center" style="width: 250px;height: 200px;">
                    <a href="{{ product.get_absolute_url }}"  class="w-25 text-center align-items-center text-decoration-none text-secondary d-flex flex-column mx-5"><p style="width: 200px;"><img src="{{result.image.url}}" style="max-height: 100px;">{{result.character.title}} {{ result.name }}</p><br/>{{ result.price }} Р</a>
                </div>
            {% endfor %}
        </div>
    </div>
{%endblock%}